51 example section in orakl docs
Bisonai/orakl-docs pull request #52
Opened 2024-03-13 01:57 UTC by KelvinThai

2024-03-26 02:34 UTC, nick-bisonai requested changes
LGTM! requested few updates.

2024-03-26 02:34 UTC, nick-bisonai commented on en/developers-guide/binaryExample.sol
why is this file written in solidity format?

2024-03-26 02:34 UTC, nick-bisonai commented on en/developers-guide/binaryExample.sol
> +```
this seems to be unrelated

2024-03-27 06:56 UTC, KelvinThai commented on en/developers-guide/binaryExample.sol
ah! my bad. habbit of an old blockchain dev

2024-03-27 07:07 UTC, merged